services:
  bot:
    image: ghcr.io/ttkindboy/ministral:master
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    container_name: skinpeek_bot

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
    container_name: skinpeek_redis
